# Generated by Django 6.0.7 on 2026-07-24 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='degree',
            field=models.CharField(choices=[('Foundation', 'foundation'), ('Associate', 'associate'), ('Bachelors', 'bachelors'), ('Masters', 'masters'), ('PHD', 'phd')], null=True),
        ),
    ]
