# Generated by Django 6.0.7 on 2026-07-24 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_user_degree'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(default='image/user/default_user.png', upload_to='image/user'),
        ),
    ]
