# Generated by Django 6.0.7 on 2026-07-24 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, default='image/user/default_user.png', null=True, upload_to='image/user'),
        ),
    ]
