# Generated by Django 6.0.7 on 2026-07-25 10:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=100)),
                ('semester', models.CharField(choices=[('semester1', 'semster1'), ('semester2', 'semster2'), ('semester3', 'semster3'), ('semester4', 'semster4'), ('semester5', 'semster5'), ('semester6', 'semster6'), ('semester7', 'semster7'), ('semester8', 'semster8')], max_length=100)),
                ('descriptions', models.TextField()),
                ('image', models.ImageField(blank=True, default='image/course/course default.png', null=True, upload_to='image/course')),
                ('credit_units', models.CharField(choices=[('1 unit', '1 unit'), ('2 unit', '2 unit'), ('3 unit', '3 unit'), ('4 unit', '4 unit')], max_length=100)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
