# Generated by Django 6.0.7 on 2026-07-27 07:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0003_comment_view_bookmark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='replied',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Course.comment'),
        ),
    ]
